# Generated by Django 5.2 on 2026-01-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(default=50, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(default=50, max_length=100),
            preserve_default=False,
        ),
    ]
