# Generated by Django 5.2 on 2026-01-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0002_jobapplication_email_jobapplication_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactquery',
            name='phone',
            field=models.CharField(default=9861524698, max_length=15),
            preserve_default=False,
        ),
    ]
