# Generated by Django 5.2 on 2026-01-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0004_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Enter experience in years'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
