# Generated by Django 5.2 on 2026-01-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0005_job_experience_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.PositiveIntegerField(),
        ),
    ]
