# Generated by Django 5.2 on 2026-01-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0006_alter_job_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactquery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contactquery',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactquery',
            name='fname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactquery',
            name='subject',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
