# Generated by Django 5.2 on 2026-01-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0007_remove_contactquery_name_remove_contactquery_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactquery',
            name='lname',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
